---
- name: Install Apache HTTP Server
  hosts: all
  become: true
  become_user: root
  tasks:
    - name: Install Apache2
      ansible.builtin.apt:
        name: "{{ apache_package }}"
        state: present
        update_cache: yes
      tags: apache_install
