- name: Install module
  hosts: all
  become: true
  become_user: ubuntu2
  tasks:
    - name: Install Apache
      ansible.builtin.apt:
        name: apache2
        state: present
      register: apache_install_result
    - name: Debug the installation result
      ansible.builtin.debug:
        var: apache_install_result.changed
    - name: Checking installed software
      ansible.builtin.debug:
        msg: Package is already Installed
      when: apache_install_result.changed == false
  tags: apache_install
