
- name: My first play
  hosts: all
  vars_files:
    - var.yaml
    - var1.yaml
  tasks:
   - name: Ping my hosts
     ansible.builtin.ping:
   - name: Print message
     ansible.builtin.debug:
       var: my_msg_var
  tags: print_message
- name: Install module
  hosts: all
  become: true
  become_user: root
  tasks:
   - name: install apace
     ansible.builtin.apt:
      name: apache2
      state: present
  tags: apache_install
- name: Check Boolean
  hosts: all
  vars_files:
    - var.yaml
  tasks:
   - name: Boolean_value
     ansible.builtin.debug:
       msg: "Variable is true"
     when: is_enabled
  tags: check_test
