---
- name: Install, configure, and verify Nginx and MySQL
  hosts: webservers
  become: yes
  roles:
    - geerlingguy.nginx
    - geerlingguy.mysql
  # Roles installed via Requirement.txt

  tasks:
    - name: Verify Nginx is installed
      command: nginx -v
      register: nginx_version
      ignore_errors: yes

    - name: Check Nginx installation
      debug:
        msg: "Nginx version: {{ nginx_version.stderr }}"
      when: nginx_version.rc == 0
      # displays the Nginx version if the previous command succeeds 

    - name: Verify Nginx service is running
      systemd:
        name: nginx
        state: started
      register: nginx_service
      ignore_errors: yes

    - name: Check Nginx service status
      debug:
        msg: "Nginx service is running"
      when: nginx_service.state == 'started'
      # confirms the service status if it is in the 'started' state.

    - name: Verify MySQL is installed
      command: mysql --version
      register: mysql_version
      ignore_errors: yes

    - name: Check MySQL installation
      debug:
        msg: "MySQL version: {{ mysql_version.stdout }}"
      when: mysql_version.rc == 0
      # displays the MySQL version if the previous command succeeds 

    - name: Verify MySQL service is running
      systemd:
        name: mysql
        state: started
      register: mysql_service
      ignore_errors: yes

    - name: Check MySQL service status
      debug:
        msg: "MySQL service is running"
      when: mysql_service.state == 'started'
      # task confirms the service status if it is in the 'started' state.
